blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailapp.urls', namespace='mailapp')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailapp/urls.py
from django.urls import path
from mailapp.apps import MailappConfig
from mailapp.views import LetterListView, LetterDetailView, LetterCreateView, LetterUpdateView, LetterDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, ClientListView, \
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView

app_name = MailappConfig.name

urlpatterns = [
    path('', LetterListView.as_view(), name='letter_list'),
    path('mailapp/<int:pk>/', LetterDetailView.as_view(), name='letter_detail'),
    path('mailapp/create', LetterCreateView.as_view(), name='letter_create'),
    path('mailapp/<int:pk>/update/', LetterUpdateView.as_view(), name='letter_update'),
    path('mailapp/<int:pk>/delete/', LetterDeleteView.as_view(), name='letter_delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_service/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_service/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, email_verification, ProfileView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

mailapp/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Класс для описания модели клиента"""
    name = models.CharField(max_length=100, verbose_name='Ф.И.О.')
    email = (models.EmailField(max_length=100, verbose_name='Контактный email', unique=True))
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)

    owner = models.ForeignKey(User, verbose_name='Менеджер', **NULLABLE, on_delete=models.SET_NULL)
    count = models.PositiveIntegerField(
        verbose_name='Количество клиентов рассылок',
        default=0
    )

    def __str__(self):
        return f'{self.name} - {self.email} \n {self.comment}'

    class Meta:
        verbose_name = 'Клиент сервиса'
        verbose_name_plural = 'Клиенты сервиса'


class Message(models.Model):
    """Класс для описания модели сообщения для рассылки"""
    letter_subject = models.TextField(verbose_name='тема письма', **NULLABLE)
    body = models.TextField(verbose_name='тело письма')

    owner = models.ForeignKey(User, verbose_name='Менеджер', **NULLABLE, on_delete=models.SET_NULL)

    def __str__(self):
        return f'Тема письма: {self.letter_subject}. \n Сообщение: {self.body}'

    class Meta:
        verbose_name = 'Сообщение для рассылки'
        verbose_name_plural = 'Сообщения для рассылки'


class NewsLetter(models.Model):
    """Класс для описания модели рассылки"""
    CREATED = 'Создана'
    STARTED = 'Запущена'
    FINISHED = 'Завершена'
    MINUTLY = 'minutly'
    DAILY = 'daily',
    WEEKLY = 'weekly',
    MONTHLY = 'monthly',

    STATUS_CHOICES = (
        ('CREATED', 'Создана'),
        ('STARTED', 'Запущена'),
        ('FINISHED', 'Завершена'),
    )

    FREQUENCY_CHOICES = (
        ('MINUTLY', 'раз в минуту'),
        ('DAILY', 'раз в день'),
        ('WEEKLY', 'раз в неделю'),
        ('MONTHLY', 'раз в месяц'),
    )
    name = models.CharField(max_length=50, verbose_name='Название рассылки', default='без названия', **NULLABLE)
    client = models.ManyToManyField(Client, verbose_name='Клиент сервиса', help_text='Укажите клиентов')
    message = models.ForeignKey(Message, verbose_name='Сообщение', on_delete=models.CASCADE, **NULLABLE)
    start_time = models.DateTimeField(verbose_name='время начала рассылки', **NULLABLE)
    end_time = models.DateTimeField(verbose_name='время окончания рассылки', **NULLABLE)
    frequency = models.CharField(verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц',
                                 choices=FREQUENCY_CHOICES,
                                 default=DAILY
                                 )
    status = models.CharField(verbose_name='Статус рассылки (например, завершена, создана, запущена)',
                              default=CREATED,
                              choices=STATUS_CHOICES
                              )
    owner = models.ForeignKey(User, verbose_name='Менеджер', **NULLABLE, on_delete=models.SET_NULL)
    count = models.PositiveIntegerField(
        verbose_name='Количество рассылок',
        default=0
    )

    def __str__(self):
        return f'{self.start_time} /n {self.frequency} /n {self.status}'

    class Meta:
        verbose_name = 'Рассылка (настройки)'
        verbose_name_plural = 'Рассылки (настройки)'
        permissions = [
            ('can_delete_newsletter', "Can delete newsletter"),
            ('can_view_newsletter', "Can view newsletter"),
            ('can_delete_client', "Can delete client"),
            ('can_view_client', "Can view client")
        ]


class Attempt(models.Model):
    """Класс для описания модели попытки рассылки"""
    LOG_SUCCESS = 'Успешно'
    LOG_FAIL = 'Неуспешно'

    STATUS_VARIANTS = [
        (LOG_SUCCESS, 'Успешно'),
        (LOG_FAIL, 'Неуспешно'),
    ]

    mailing_parameters = models.ForeignKey(NewsLetter, on_delete=models.CASCADE,
                                           verbose_name='параметры рассылки', **NULLABLE)
    time = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True)
    status = models.CharField(verbose_name='статус попытки (успешно / не успешно)', choices=STATUS_VARIANTS)
    server_response = models.CharField(verbose_name='ответ почтового сервера, если он был')

    def __str__(self):
        return f'{self.time} /n {self.status} /n {self.server_response}'

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

mailapp/forms.py
from django.forms import ModelForm, BooleanField

from mailapp.models import Message, Client, NewsLetter


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, fild in self.fields.items():
            if isinstance(fild, BooleanField):
                fild.widget.attrs['class'] = "form-check-input"
            else:
                fild.widget.attrs['class'] = "form-control"


class NewsLetterForm(StyleFormMixin, ModelForm):
    class Meta:
        model = NewsLetter
        fields = '__all__'


class NewsLetterModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = NewsLetter
        exclude = ('owner', 'count')


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = '__all__'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

mailapp/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.models import Blog
from mailapp.forms import NewsLetterForm, NewsLetterModeratorForm, MessageForm, ClientForm
from mailapp.models import NewsLetter, Client, Message


class LetterListView(ListView):
    model = NewsLetter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_newsletters'] = NewsLetter.objects.count()
        context['active_newsletters'] = NewsLetter.objects.filter(status='CREATED').count()
        context['unique_clients'] = Client.objects.distinct().count()
        all_posts = list(Blog.objects.filter(is_published=True))
        context['random_posts'] = sample(all_posts, min(len(all_posts), 3))
        return context


class LetterDetailView(DetailView):
    model = NewsLetter


class LetterCreateView(CreateView, LoginRequiredMixin):
    model = NewsLetter
    form_class = NewsLetterForm
    success_url = reverse_lazy('mailapp:letter_list')

    def form_valid(self, form):
        letter = form.save()
        user = self.request.user
        letter.owner = user
        letter.save()
        return super().form_valid(form)


class LetterUpdateView(LoginRequiredMixin, UpdateView):
    model = NewsLetter
    form_class = NewsLetterForm
    success_url = reverse_lazy('mailapp:letter_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return NewsLetterForm
        if (user.has_perm('mailapp.can_delete_newsletter') and user.has_perm(
                'mailapp.can_view_newsletter')):
            return NewsLetterModeratorForm
        raise PermissionDenied


class LetterDeleteView(DeleteView):
    model = NewsLetter
    success_url = reverse_lazy('mailapp:letter_list')


# crud для сообщения
class MessageListView(ListView):
    model = Message


class MessageDetailView(DetailView):
    model = Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailapp:message_list')


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailapp:message_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return NewsLetterForm
        if (user.has_perm('mail_service.can_delete_newsletter') and user.has_perm(
                'mailapp.can_view_newsletter') and user.has_perm('mailapp.can_delete_client')
                and user.has_perm('mailapp.can_view_client')):
            return NewsLetterModeratorForm
        raise PermissionDenied


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('mailapp:message_list')


# crud для клиента
class ClientListView(ListView):
    model = Client

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['client_count'] = Client.objects.count()
        return context


class ClientDetailView(DetailView):
    model = Client


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailapp:client_list')


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailapp:client_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return NewsLetterForm
        if (user.has_perm('mail_service.can_delete_newsletter') and user.has_perm(
                'mail_service.can_view_newsletter') and user.has_perm('mailapp.can_delete_client')
                and user.has_perm('mailapp.can_view_client')):
            return NewsLetterModeratorForm
        raise PermissionDenied


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailapp:client_list')


def index_data(request):
    count_mailing_items = NewsLetter.objects.count()
    count_active_mailing_items = NewsLetter.objects.filter(status='STARTED').count()
    count_unic_clients = Client.objects.values_list('email', flat=True).count()
    random_blogs = Blog.objects.order_by('?')[:3]
    context = {'count_mailing_items': count_mailing_items,
               'count_active_mailing_items': count_active_mailing_items,
               'count_unic_clients': count_unic_clients,
               'random_blogs': random_blogs,
               }

    return context


def index_data(request):
    newsletter_count = NewsLetter.objects.count()
    count_active_mailing_items = NewsLetter.objects.filter(status='STARTED').count()
    client_count = Client.objects.count()
    random_blogs = Blog.objects.order_by('?')[:3]
    context = {'count_mailing_items': newsletter_count,
               'count_active_mailing_items': count_active_mailing_items,
               'count_unic_clients': client_count,
               'random_blogs': random_blogs,
               }

    return render(request, 'mailapp/base.html', context)

mailapp/templates/mailapp/attempts_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="mb-3">
</div>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for object in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.date_and_time }}</h4>
            </div>
            <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Статус: {{ object.is_success }}</li>
                </ul>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Ответ сервера: {{ object.answer }}</li>
                </ul>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>Рассылка: {{ object.mailing_parameters }}</li>
                </ul>
            </div>
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

mailapp/templates/mailapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'mailapp:letter_list'%}">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'blog:blog_list'%}">Блог</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Клиенты</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'mailapp:client_list'%}">Список клиентов</a>
                    <a class="dropdown-item" href="{% url 'mailapp:client_create' %}">Добавить клиента</a>
                    <a class="dropdown-item" href="#"></a>
                </div>

            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown02" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Сообщения для рассылки</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'mailapp:message_list'%}">Список сообщений</a>
                    <a class="dropdown-item" href="{% url 'mailapp:message_create' %}">Создать новое сообщение</a>
                </div>
            </li>
        </ul>
        <nav class="ms-5">
            {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
            {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </nav>
    </div>
</nav>

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Сервис рассылки</h1>
            <p> Рассылки для информирования и привлечения клиентов</p>
        </div>
    </div>



    {% block content %}
    {% endblock %}

    <!-- /container -->

</main>


<footer class="container">
    <p>&copy; {% now 'Y' %}</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

mailapp/templates/mailapp/client_detail.html
{% extends 'mailapp/base.html'%}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">Клиент: {{object.name}}  </p>
                    <p class="card-text">Почта: {{object.email}}  </p>
                    <p class="card-text">Комментарий: {{object.comment}}  </p>

                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'mailapp:letter_list'%}"
                               role="button">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailapp/templates/mailapp/client_form.html
{% extends 'mailapp/base.html' %}
{% block content %}

<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3 text-center">

            <h4 class="my-0 fw-normal">Клиент</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
            </form>
        </div>
        <div class="card-footer">
             <a href="{% url 'mailapp:client_list' %}" class=" btn btn-lg btn-primary">Отмена</a>
        </div>
    </div>
</div>
{% endblock %}

mailapp/templates/mailapp/client_list.html
{% extends 'mailapp/base.html' %}

{% block content %}

<div class="mb-3">
    <a href="{% url 'mailapp:client_create' %}" class="w-100 btn btn-lg btn-outline-primary">Добавить клиента</a>
</div>
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for object in object_list %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.name }}</h4>
            </div>
            <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Email: {{ object.email }}</li>
                    <li>Комментарий: {{ object.comment }}</li>

                </ul>
                {% if perms.mailapp.can_delete_client and perms.mailapp.can_view_client or user == letter.owner %}
                <a href="{% url 'mailapp:client_update'  object.pk %}" type="button"
                   class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                {% endif %}

            </div>
            <div class="card-footer">
                <a href="{% url 'mailapp:client_delete'  object.pk %}" type="button"
                   class="w-100 btn btn-lg btn-outline-primary">Удалить</a>
            </div>

        </div>
    </div>

    {% endfor%}
</div>
{% endblock %}

mailapp/templates/mailapp/mail_list.html
{% extends 'mailapp/base.html'%}
{% block content %}

<div class="container">
    <div class="row">
        {% for letter in letters %}
        <div class="col-md-4">
            <h2>Рассылка</h2>
            <p> {{ letter.status }}</p>
            <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div>
        {% endfor %}
    </div>
    <hr>
</div>
{% endblock %}

mailapp/templates/mailapp/message_confirm_delete.html
{% extends 'mailapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p> Хотите удалить "{{ object.status }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a class="btn btn-primary" href="{% url 'mailapp:message_list'%}" role="button">Назад</a>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}

mailapp/templates/mailapp/message_detai.html
{% extends 'mailapp/base.html'%}
{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <p class="card-text">Тема письма: <ul> {{ object.letter_subject }} </ul> </p>
                    <p class="card-text">Сообщение: <ul> {{ object.body }} </ul> </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'mailapp:message_list'%}"
                               role="button">Назад</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailapp/templates/mailapp/message_form.html
{% extends 'mailapp/base.html' %}
{% block content %}

<div class="col">
    <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3 text-center">

            <h4 class="my-0 fw-normal">Сообщение</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
            </form>
        </div>
        <div class="card-footer">
             <a href="{% url 'mailapp:message_list' %}" class=" btn btn-lg btn-primary">Отмена</a>
        </div>
    </div>
</div>
{% endblock %}

mailapp/templates/mailapp/message_list.html
{% extends 'mailapp/base.html' %}

{% block content %}

<div class="mb-3">
    <a href="{% url 'mailapp:message_create' %}" class="w-100 btn btn-lg btn-outline-primary">Создать сообщение</a>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">


    {% for object in object_list %}

    <div class="col-4">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.letter_subject }}</h4>
            </div>
            <div class="card-body">

                <ul class="list-unstyled mt-3 mb-4">
                    <li>Текст сообщения: {{ object.body }}</li>

                </ul>
                {% if perms.mailapp.can_delete_newsletter and perms.mailapp.can_view_newsletter or user == letter.owner %}
                <a href="{% url 'mailapp:message_update'  object.pk %}" type="button"
                   class="w-100 btn btn-lg btn-outline-primary">Редактировать</a>
                {% endif %}


            </div>
            <div class="card-footer">
                <a href="{% url 'mailapp:message_delete'  object.pk %}" type="button"
                   class="w-100 btn btn-lg btn-outline-primary">Удалить</a>
            </div>

        </div>
    </div>

    {% endfor%}
</div>
{% endblock %}

mailapp/templates/mailapp/newsletter_list.html
{% extends 'mailapp/base.html'%}
{% block content %}

<div class="container">
    <p><a class="btn btn-primary btn-lg" href="{% url 'mailapp:letter_create' %}" role="button">Создать рассылку &raquo;</a></p>
    <div class="row">

        {% for letter in object_list %}
        <div class="col-md-4">
            <h2>{{ letter.name }}</h2>

            <p class="card-text">{{letter.message}}</p>
            <p><a class="btn btn-success " href="{% url 'mailapp:letter_detail' letter.pk %}" role="button">Посмотреть &raquo;</a></p>
            {% if perms.mailapp.can_delete_newsletter and perms.mailapp.can_view_newsletter or user == letter.owner %}
            <p><a class="btn btn-warning " href="{% url 'mailapp:letter_update' letter.pk %}" role="button">Редактировать &raquo;</a></p>
            {% endif %}
            <p><a class="btn btn-secondary " href="{% url 'mailapp:letter_delete' letter.pk %}" role="button">Удалить &raquo;</a></p>
        </div>

        {% endfor %}
    </div>

<div class=".col-md-4 .ml-auto">
      <div class="card text-center">
        <div class="card-body">
          <h5 class="card-title">Статистика:</h5>
          <p class="card-text">количество рассылок всего {{total_newsletters}}</p>
            <p>количество активных рассылок {{active_newsletters}}</p>
              <p>количество уникальных клиентов для рассылок {{unique_clients}}</p>
        </div>
      </div>
    </div>
    <div class="container px-4 py-5">
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div class="fs-2 text-body-emphasis">
                <h2>Статьи из блога</h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    {% for post in random_posts %}
                    <li class="list-group-item">
                        <h3>{{ post.title }}</h3>
                        <p>{{ post.content|truncatewords:20 }}</p>
                        <a class="btn btn-primary" href="{% url 'blog:blog_detail' post.id %}">Читать далее</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <hr>
    </div>
</div>

{% endblock %}