blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailapp.urls', namespace='mailapp')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    """Класс для описания модели блога"""
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    slug = models.CharField(max_length=100, verbose_name="Slug", **NULLABLE)
    content = models.TextField(verbose_name="содержимое статьи", **NULLABLE)
    preview = models.ImageField(
        upload_to="blog/preview", verbose_name="изображение", **NULLABLE
    )
    created_at = models.DateField(**NULLABLE, verbose_name="дата публикации")
    number_of_views = models.IntegerField(
        verbose_name="Количество просмотров", default=0
    )
    is_published = models.BooleanField(default=True, verbose_name="Опубликован")

    def __str__(self):
        return f"{self.title} {self.content} {self.created_at} {self.number_of_views}"

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

blog/views.py
from django.shortcuts import render


from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from blog.models import Blog


class BlogListView(ListView):
    model = Blog
    fields = ("title", "content", "preview", "created_at")
    success_url = reverse_lazy("blog:blog_list")


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ("title", "content", "preview", "created_at")
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ("title", "content", "preview", "created_at")

    def get_success_url(self):
        return reverse("blog:blog_detail", kwargs={"pk": self.object.pk})


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailapp/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-2">
                <div class="card">
                    <div class="card-body">
                        <form method='post'>
                            {% csrf_token %}
                            <p>Хотите удалить "{{object.title}}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary" xmlns="http://www.w3.org/1999/html">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{blog.preview|media_filter }}">
            <div class="card-body">
              <p class="card-text">{{ blog.title | title }} ({{ blog.slug}})</p>
              <p class="card-text">Содержимое:  {{ blog.content | title }}</p>
              <p class="card-text">Дата публикации: {{ blog.created_at }}</p>
              <p class="card-text">Количество просмотров:  {{ blog.number_of_views }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-info" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                  <a class="btn btn-warning" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailapp/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button><a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отменить</a>
                         </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
     <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Блог</h1>
            <p class="lead"></p>
        <a class="btn btn-primary my-2" href="{% url 'blog:blog_create' %}">Создать новый блог</a>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for blog in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ blog.preview | media_filter }}">
                    <div class="card-body">
                        <p class="card-text">{{ blog.title | title }}</p>
                        <p class="card-text">Содержимое: {{ blog.content | title }}</p>
                        <p class="card-text">Дата публикации: {{ blog.created_at }}</p>
                        <p class="card-text">Количество просмотров: {{ blog.number_of_views }}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn">
                                <a class="btn btn-success" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Посмотреть</a>
                                <a class="btn btn-warning" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}