blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('list/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete')

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailapp.urls', namespace='mailapp')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailapp/urls.py
from django.urls import path
from mailapp.apps import MailappConfig
from mailapp.views import LetterListView, LetterDetailView, LetterCreateView, LetterUpdateView, LetterDeleteView, \
    MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView, ClientListView, \
    ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView

app_name = MailappConfig.name

urlpatterns = [
    path('', LetterListView.as_view(), name='letter_list'),
    path('mailapp/<int:pk>/', LetterDetailView.as_view(), name='letter_detail'),
    path('mailapp/create', LetterCreateView.as_view(), name='letter_create'),
    path('mailapp/<int:pk>/update/', LetterUpdateView.as_view(), name='letter_update'),
    path('mailapp/<int:pk>/delete/', LetterDeleteView.as_view(), name='letter_delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_service/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_service/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, email_verification, ProfileView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField("Email address", unique=True)
    avatar = models.ImageField(
        upload_to="users/avatars",
        verbose_name="аватар",
        blank=True,
        null=True,
        help_text="Загрузите свой аватар",
    )
    phone = models.CharField(
        max_length=35,
        verbose_name="номер телефона",
        blank=True,
        null=True,
        help_text="Введите номер телефона",
    )
    token = models.CharField(
        max_length=100, verbose_name="Token", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
import secrets
import string

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейдите по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def reset_password(request):
    context = {
            'success_message': 'Пароль успешно сброшен. Новый пароль был отправлен на адрес Вашей электронной почты.',
        }

    if request.method == 'POST':
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        characters = string.ascii_letters + string.digits
        characters_list = list(characters)
        random.shuffle(characters_list)
        password = ''.join(characters_list[:10])
        user.set_password(password)
        user.save()

        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш пароль для доступа на сайт изменен:\n {password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
            )

        return render(request, 'users/reset_password.html', context)

    return render(request, 'users/reset_password.html')

users/templates/users/login.html
{% extends 'mailapp/base.html' %}
{% block content %}
<div class="col-6">
    <form class="row" method='post' enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                      </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                  <a href="{% url 'users:reset_password' %}" type="submit" class="btn btn-warning">
                        Восстановить пароль
                    </a>
                </div>
            </div>
</form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailapp/base.html' %}
{% block content %}
<div class="col-6">
    <form class="row" method='post' enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <h3 class="card-title">
                    Регистрация
                </h3>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                </button>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'mailapp/base.html'%}
{% block content %}

<div class="col-12">
    <form class="row" method="post">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <input class="form-control mb-2" name="email" placeholder="Введите почту, для сброса пароля"/>
                    <button type="submit" class="btn btn-success">Восстановить пароль</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailapp/base.html' %}
{% block content %}
<div class="col-6">
    <form class="row" method='post' enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <h3 class="card-title">
                    Профиль
                </h3>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
                <div class="card-footer">
                    <a href="{% url 'mailapp:letter_list' %}" class=" btn btn-lg btn-primary">Отмена</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}